const BASE_URL = '/api/'
const NOTES_ENDPOINT = `${BASE_URL}notes/`
const ORGANIZATIONS_ENDPOINT = `${BASE_URL}organizations/`
const USERS_ENDPOINT = `${BASE_URL}users/`
const STUDENTS_ENDPOINT = `${BASE_URL}students/`
const INSTRUCTORS_ENDPOINT = `${BASE_URL}instructors/`
const REGISTRATION_ENDPOINT = `${BASE_URL}register/`
const COURSES_ENDPOINT = `${BASE_URL}courses/`
const ASSIGNMENT_ENDPOINT = `${BASE_URL}assignment/`
const ASSIGNMENTSUBMISSION_ENDPOINT = `${BASE_URL}assignmentSubmission/`
const COURSE_FILE_ENDPOINT = `${BASE_URL}files/`
const ANNOUNCEMENTS_ENDPOINT = `${BASE_URL}announcements/`
const DISCUSSIONBOARD_ENDPOINT = `${BASE_URL}discussionboards/`
const COMMENTS_ENDPOINT = `${BASE_URL}comments/`
const ANSWERS_ENDPOINT = `${BASE_URL}answers/`
const REPLIES_ENDPOINT = `${BASE_URL}replies/`
const POST_ENDPOINT = `${BASE_URL}posts/`
const COURSE_MATERIALS_ENDPOINT = `${BASE_URL}materials/`
const COURSE_MEDIA_ENDPOINT = `${BASE_URL}media/`

module.exports = {
    BASE_URL,
    NOTES_ENDPOINT,
    ORGANIZATIONS_ENDPOINT,
    USERS_ENDPOINT,
    STUDENTS_ENDPOINT,
    INSTRUCTORS_ENDPOINT,
    ASSIGNMENT_ENDPOINT,
    ASSIGNMENTSUBMISSION_ENDPOINT,
    REGISTRATION_ENDPOINT,
    COURSES_ENDPOINT,
    COURSE_FILE_ENDPOINT,
    ANNOUNCEMENTS_ENDPOINT,
    DISCUSSIONBOARD_ENDPOINT,
    COMMENTS_ENDPOINT,
    ANSWERS_ENDPOINT,
    REPLIES_ENDPOINT,
    POST_ENDPOINT,
    COURSE_MATERIALS_ENDPOINT,
    COURSE_MEDIA_ENDPOINT
}